POST http://localhost:3000/api/v1
Content-Type: application/json
Accept: application/json

{
  "name": "Dakota",
  "email": "dakota@email.com",
  "subject": "hello there",
  "text": "this is a test"
}